### ISSUE TITLE
Error en afipws multicompañia

### ISSUE THREAD

**Issue by MatiasBanega** [codize-app/odoo-argentina#17]
Hola Ignacio y equipo, en este caso les traigo un error que se esta presentando en la v15. 

cuando alguien tiene multicompañía y el usuario tiene asignado como predeterminada una compañía de las dos. Tengo varios usuarios que tienen una compañía como predeterminada de las dos compañías, cuando facturan con la predeterminada anda todo ok ahora cuando quieren validar la factura en afip con la otra compañía en la cual tienen permisos les aparece esta restricción. Ambos al facturar están parados en la compañía de la cual es la factura

![image](https://github.com/codize-app/odoo-argentina/assets/30711494/8418a234-82aa-48d5-9f48-38c250e7ff97)

si yo quito esa restricción luego tengo el siguiente problema

![image](https://github.com/codize-app/odoo-argentina/assets/30711494/e8a90a21-8ce8-48de-8cf6-719e966627af)

Siendo que el certificado es correcto y funciona, me marca como que no tiene certificado cuando si lo tiene

O sea en ambas compañias los certificados están ok.

Espero puedan verlo rapidamente

**Comment by ibuioli** [comment]
Buenas, el primer error es sacando la restricción, no debería estar. En el caso del segundo, es porque no está confirmado para producción. Eso tiene que ver con los parámetros del sistema o con el certificado. Tenemos clientes en 15 CE que lo están usando, fijate como se dio de alta.

**Comment by MatiasBanega** [comment]
Hola Ignacio, ambos estan en producción como debe ser.

![image](https://github.com/codize-app/odoo-argentina/assets/30711494/1fb9e37a-e457-42d2-970e-8e15c5d3e104)

**Comment by ibuioli** [comment]
Buenas, revisamos y sistemáticamente se fueron corrigiendo los permisos multicompañía en la versión 16, recién agregué la última, es algo que se arrastró de versiones viejas.
