### ISSUE TITLE
Permiso Para Crear Recibos de Pago

### ISSUE THREAD

**Issue by GonzaloVich** [codize-app/odoo-argentina#6]
Buenos Días, cuando se quiere registrar el pago directamente desde una factura con el modulo account_payment_group instalado no lo permite y tira un error de permiso de ir.config_parameter.
![image](https://user-images.githubusercontent.com/68303239/208700634-eec8af87-c83f-4cdc-a5f9-d60ab2e90bbe.png)
Esto ocurre si el usuario en cuestion no tiene permisos de "Ajuste" en "Administración".  Esto es un problema si el usuario no es un administrador y solo es un agente de facturacion o de ventas, ya que pueden ver y tocar todas las configuraciones del Odoo, de momento lo estamos solventando poniendo "sudo()" en las lineas 692 y 707 de account_payment_group.py, pero no se si es lo correcto.
![image](https://user-images.githubusercontent.com/68303239/208701625-e41f5922-7f74-42bc-975d-ecd2e2ee423d.png)
¿Seria esta la forma correcta de arreglar el problema?

**Comment by ibuioli** [comment]
Buenas observación, no nos había pasado pero la solución es correcta, ya lo subimos.
