### ISSUE TITLE
impresión del Nombre del comprobante

### ISSUE THREAD

**Issue by wgtoneatto** [codize-app/odoo-argentina#8]
Hola Ignacio, buen día, estoy trabajando con odoo 15 en ubuntu 20.04 lts, con localización argentina codize,  
en la impresión de factura electronica: "l10n_ar_report_fe", 
al imprimir nombre del comprobante, imprime = "o.l10n_latam_document_type_id.name"
y deberia imprimir:  "o.l10n_latam_document_type_id.report_name"

creo que debería ser así, 
gracias.

**Comment by ibuioli** [comment]
Vas a tener que aportar más información, no se a cual archivo te referis.

**Comment by wgtoneatto** [comment]
en el reporte de la factura electronica:
https://github.com/codize-app/odoo-argentina/tree/15.0/l10n_ar_report_fe/report_invoice_fe.xml
en la linea 42, imprime:
  "o.l10n_latam_document_type_id.name"
imprime ejemplo: = "FACTURAS B"
y sería
 "o.l10n_latam_document_type_id.report_name"
imprime ejemplo: = "FACTURA"

**Comment by ibuioli** [comment]
Tengo entendido que está bien igualmente, pero bueno, ahi lo modifiqué.
