### ISSUE TITLE
Factura Rectificativa de Cliente

### ISSUE THREAD

**Issue by wgtoneatto** [codize-app/odoo-argentina#9]
Hola Ignacio, buen día, trabajo con odoo 15, en ubuntu 20.04 lts, localización argentina codize.
Al hacer una Nota de Credito, me muestra este error:
"Error de usuario

AFIP Validation Error. 10197: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc."

que puede estar pasando?

**Comment by ibuioli** [comment]
Tenés que crear la factura rectificativa para que funcione la NC, porque el sistema no tiene comprobante sino.
